name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  jdtls_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Ensure Java code compiles
        working-directory: pde
        run: mvn clean compile
  vscode_extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Ensure TypeScript code compiles
        run: npm run vscode:prepublish
      - name: Lint TypeScript code with eslint
        run: npm run lint